### ISSUE TITLE
Login failure after changing primary GitHub email address

### ISSUE THREAD

**Issue by ekrzeptowski** [nerdbord/good-dev-hunting-app#201]
## Description
After changing primary email address, I get the following error message:
`Invalid prisma.user.create() invocation:`
`Unique constraint failed on the fields: ('username')`

## Steps to reproduce
1. Go to https://github.com/settings/emails and change your primary email address.
2. Logout and try to login again with the new email address.
3. See the error message.

**Comment by Sumick** [comment]
It should work now @ekrzeptowski :-) Thank you!

**Comment by Sumick** [comment]
Fix merged
