### ISSUE TITLE
Issue: team members redirect on click (home page)

### ISSUE THREAD

**Issue by szymonkadas** [nerdbord/good-dev-hunting-app#265]
After clicking on one of team members it redirects you to the profiles search page, instead of profile.
![obraz](https://github.com/nerdbord/good-dev-hunting-app/assets/133753432/9d2999d9-d522-4199-bbaa-85832cf92e64)
![obraz](https://github.com/nerdbord/good-dev-hunting-app/assets/133753432/d16d432f-a7fc-4d97-a870-2b63c945e000)
Solution: put "/p" instead of "profiles" before username in links.

**Comment by Sumick** [comment]
Fixed in https://github.com/nerdbord/good-dev-hunting-app/pull/268
