### ISSUE TITLE
Wrong link in email

### ISSUE THREAD

**Issue by ssynowiec** [nerdbord/good-dev-hunting-app#320]
After profile approve "Open your profile" link in mail redirect to bad URL.

Open link redirect to https://www.devhunting.co/profiles/[username] and return `Not Found Could not find requested resource`

https://github.com/nerdbord/good-dev-hunting-app/assets/52856724/270ef44f-90b0-47ac-9981-c5858eb1172e

**Comment by Sumick** [comment]
Thanks for catching this! We were changing profile URL location, it works now :-)
